name: CI Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    name: Lint, test, build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint typescript
        run: npm run lint:ts

      - name: Lint styles
        run: npm run lint:scss

      - name: Run unit tests
        run: npm run unit

      - name: Build
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook
